INSERT OR IGNORE INTO artist_type (id, name) VALUES (1, 'Person');
INSERT OR IGNORE INTO artist_type (id, name) VALUES (2, 'Group');
INSERT OR IGNORE INTO artist_type (id, name) VALUES (3, 'Other');

INSERT OR IGNORE INTO country (id, iso_code, name) VALUES (107, 'JP', 'Japan');

INSERT OR IGNORE INTO gender (id, name) VALUES (1, 'Male');
INSERT OR IGNORE INTO gender (id, name) VALUES (2, 'Female');
INSERT OR IGNORE INTO gender (id, name) VALUES (3, 'Other');

INSERT OR IGNORE INTO medium_format (id, name) VALUES (1, 'CD');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (2, 'DVD');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (3, 'SACD');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (4, 'DualDisc');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (6, 'MiniDisc');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (7, 'Vinyl');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (8, 'Cassette');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (12, 'Digital Media');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (13, 'Other');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (17, 'HD-DVD');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (20, 'Blu-ray');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (22, 'VCD');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (28, 'UMD');
INSERT OR IGNORE INTO medium_format (id, name) VALUES (32, 'Videotape');
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (5, 'LaserDisc', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (9, 'Cartridge', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (10, 'Reel-to-reel', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (11, 'DAT', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (14, 'Wax Cylinder', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (15, 'Piano Roll', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (16, 'DCC', 13);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (21, 'VHS', 32);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (23, 'SVCD', 22);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (24, 'Betamax', 32);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (25, 'HDCD', 1);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (29, '7" Vinyl', 7);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (30, '10" Vinyl', 7);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (31, '12" Vinyl', 7);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (26, 'USB Flash Drive', 12);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (27, 'slotMusic', 12);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (18, 'DVD-Audio', 2);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (19, 'DVD-Video', 2);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (33, 'CD-R', 1);
INSERT OR IGNORE INTO medium_format (id, name, parent) VALUES (34, '8cm CD', 1);
